# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_EVENT_EVENTTYPE = descriptor.EnumDescriptor(
  name='EventType',
  full_name='Event.EventType',
  filename='EventType',
  values=[
    descriptor.EnumValueDescriptor(
      name='INCREMENT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DECREMENT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TIME', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_EVENT = descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename='recieve.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='Event.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_type', full_name='Event.event_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='Event.value', index=2,
      number=3, type=17, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sample_rate', full_name='Event.sample_rate', index=3,
      number=4, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _EVENT_EVENTTYPE,
  ],
  options=None)


_EVENT.fields_by_name['event_type'].enum_type = _EVENT_EVENTTYPE

class Event(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENT

